2024-07-10T08:05:43.145468 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2cfdb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:05:44.231413 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2c9d640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:05:45.282010 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2ceffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:05:46.440751 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2cfda60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:05:47.481897 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2c9de80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-10T08:05:48.693381 - Erreur de connexion: HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0aa2cab9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
